orders:
  id: integer
  number: varchar
  item_total: decimal
  total: decimal
  ship_total: decimal
  state: varchar
  adjustment_total: decimal
  user_id: varchar
  created_at: datetime
  updated_at: datetime
  completed_at: datetime
  payment_total: decimal
  shipment_state: varchar
  payment_state: varchar
  email: varchar
  special_instructions: text
  channel: varchar
  included_tax_total: decimal
  additional_tax_total: decimal
  currency: varchar
  total_quantity: integer
  token: varchar
  checkout_steps: varchar

line_items:
  id: integer
  number: varchar
  quantity: integer
  price: decimal
  total: decimal
  variant_id: integer
  variant_name: varchar
  sku: varchar
  variant_price: decimal
  weight: decimal
  height: decimal
  width: decimal
  depth: decimal
  is_master: boolean
  cost_price: decimal
  permalink: varchar
  description: text
  in_stock: boolean
  created_at: datetime
  updated_at: datetime

sales:
  id: integer
  order_number: varchar
  state: varchar
  channel: varchar
  currency: varchar
  quantity: integer
  price: decimal
  variant_id: integer
  total: decimal
  order_shipment_state: varchar
  order_payment_state: varchar
  variant_name: varchar
  variant_sku: varchar
  variant_price: decimal
  variant_weight: decimal
  variant_height: decimal
  variant_width: decimal
  variant_depth: decimal
  variant_master: boolean
  variant_total: decimal
  variant_quantity: integer
  in_stock: boolean
  cost_price: decimal
  description: text
  image_url: varchar
  shipment_id: integer
  shipment_number: varchar
  shipment_cost: decimal
  shipment_shipped_at: varchar
  shipment_state: varchar
  stock_location_name: varchar
  billed_to_firstname: varchar
  billed_to_lastname: varchar
  billed_to_address1: varchar
  billed_to_city: varchar
  billed_to_zipcode: varchar
  billed_to_phone: varchar
  billed_to_company: varchar
  billed_to_state: varchar
  billed_to_country: varchar
  shipped_to_firstname: varchar
  shipped_to_lastname: varchar
  shipped_to_address1: varchar
  shipped_to_city: varchar
  shipped_to_zipcode: varchar
  shipped_to_phone: varchar
  shipped_to_company: varchar
  shipped_to_state: varchar
  shipped_to_country: varchar  
  order_created_at: datetime
  order_updated_at: datetime
  order_completed_at: datetime



